---
title: 二十五、Go 语言 – 错误处理
abbrlink: 68ef1eab
categories: 
tags: 
date: 
updated: 
top_img: https://www.bing.com/th?id=OHR.BrockenSpecter_IT-IT0039522504_UHD.jpg
cover: https://www.bing.com/th?id=OHR.BridgeofSighs_IT-IT8041393229_UHD.jpg
keywords: 
---
# 二十五、Go 语言 – 错误处理

Go 语言通过内置的错误接口提供了非常简单的错误处理机制

Go 语言中的错误处理分为五个步骤

1、 生成错误

2、 返回错误

3、 接收错误

4、 错误判断

5、 处理错误

看起来很多，但其实每个都是一句话的事

### 1. 定义错误类型

Go 语言提供了 error interface 类型来生成错误

error 类型是一个接口类型，它的定义如下：

```GO
type error interface {
    Error() string
}
```

我们可以在代码中通过实现 error 接口类型来生成错误信息

```GO
errors.New("这里定义错误消息")
```

### 2. 返回错误

Go 语言没有其它语言那样的 `try...catch...except..finall` 的错误处理机制，它简单的直接返回错误给调用者，让调用者自己处理错误

Go 语言函数通常在最后的返回值中返回错误信息

```GO
func Sqrt(f float64) (float64, error) {
    if f < 0 {
        return 0, errors.New("math: square root of negative number")
    }
    // 实现
}
```

### 3. 接收错误

因为函数会返回错误，所以我们可以定义一个变量来接收错误，Go 社区推荐使用 `err` 作为变量名

下面的代码，在调用 Sqrt 的时候传递的一个负数，然后就得到了 non-nil 的error 对象

```GO
result, err:= Sqrt(-1)
```

### 4. 错误判断

我们可以将 err 变量与 nil 比较，如果结果为 true 则表示没有错误，反之则有错误

我们通常使用 if 语句 来判断错误

```GO
if err != nil {
   // 错误处理代码
}
```

### 5. 错误处理

既然知道了错误，那么我们就可以处理错误了

错误处理一般有两种，一种是输出错误然后中断程序执行，另一种是记录错误然后忽略

下面的代码我们直接输出错误，然后继续执行

```GO
if err != nil {
   fmt.Println(err)
}
```

是不是很简单，比起 try 语句中那么复杂的处理机制，这个真是简单明了

### 范例

```GO
package main

import (
    "fmt"
)

// 定义一个 DivideError 结构
type DivideError struct {
    dividee int
    divider int
}

// 实现   `error` 接口
func (de *DivideError) Error() string {
    strFormat := `
    Cannot proceed, the divider is zero.
    dividee: %d
    divider: 0
`
    return fmt.Sprintf(strFormat, de.dividee)
}

// 定义 `int` 类型除法运算的函数
func Divide(varDividee int, varDivider int) (result int, errorMsg string) {
    if varDivider == 0 {
        dData := DivideError{
            dividee: varDividee,
            divider: varDivider,
        }
        errorMsg = dData.Error()
        return
    } else {
        return varDividee / varDivider, ""
    }

}

func main() {

    // 正常情况
    if result, errorMsg := Divide(100, 10); errorMsg == "" {
        fmt.Println("100/10 = ", result)
    }
    // 当被除数为零的时候会返回错误信息
    if _, errorMsg := Divide(100, 0); errorMsg != "" {
        fmt.Println("errorMsg is: ", errorMsg)
    }

}
```

编译运行以上 Go 语言范例，输出结果如下

```
$ go run main.go 
100/10 =  10
errorMsg is:  
    Cannot proceed, the divider is zero.
    dividee: 100
    divider: 0
```